### ISSUE TITLE
Fails when Mapbox token is missing

### ISSUE THREAD

**Issue by bunsenmcdubbs** [MaineDSA/generate_fake_membership_list#12]
Initialization code requires `.mapbox_token` to exist (also missing from documentation AFAICT). IMV, this should be optional and degrade gracefully if the token is missing. I've worked around this for my purposes by commenting out the offending code.

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/andrew/src/generate_fake_membership_list/generate_fake_list.py", line 13, in <module>
    from utils.fake_addresses import (
  File "/Users/andrew/src/generate_fake_membership_list/utils/fake_addresses.py", line 11, in <module>
    geocoder = Geocoder(access_token=Path(".mapbox_token").read_text(encoding="UTF-8"))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1256, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1242, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1110, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '.mapbox_token'
```

**Comment by bmos** [comment]
This is now fixed :)
